### PR TITLE
Add project

### PR DESCRIPTION
**Pull request by zerefwayne**
### @WickedBrat1 The next/previous buttons do not work. Please resolve that.

image
image

### CODE REVIEW

**Comment by zerefwayne** [comment]
@WickedBrat1 

image

**Comment by WickedBrat1** [comment]
@zerefwayne Please make it full screen and the image should cover all the right half of the screen. Left half should be for the form

**Comment by WickedBrat1** [comment]
Also copy the package-lock.json file to your project from the repo

**Comment by zerefwayne** [comment]
image

**Pull request merged**
