### PR TITLE
Project View Designed

### PR DESCRIPTION
**Pull request by zerefwayne**
image

### CODE REVIEW

**Comment by WickedBrat1** [comment]
Looks good, but I'm not sure about the description on the right sidebar though. And what is the text there though.
Add an icon for editing the field as well

**Comment by zerefwayne** [comment]
@WickedBrat1 The project description that a person will enter.

Where will the icon look good?

**Comment by WickedBrat1** [comment]
@zerefwayne I suppose we can use the left panel to display the info of project. Also what do you think of a case when there exists no issue for the project and it's just been created.
Th icon would go on the top right of the box that contains the comment

**Comment by zerefwayne** [comment]
@WickedBrat1 When there is no issue, a create new issue heading will be displayed in center and a button to redirect to Add Issue form.

**Comment by WickedBrat1** [comment]
What about having a default page that displays project info. I think that'll be better. Like number of people that have taken part in discussion of the project etc tc. The project info can and will be extended later on. I think it's better to have a display for that too.

**Comment by zerefwayne** [comment]
Yeah a great idea. A dashboard page which also gives info about the project. I'll sketch one and implement it. Until then you can merge this and we can starting linking it to database

**Comment by WickedBrat1** [comment]
SGTM! Merging.

**Pull request merged**
